services:
  app:
    build:
      context: .
      args:
        PHP_VERSION: "8.4"
    image: mvc-framework
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity
    environment:
      XDEBUG_MODE: coverage,debug,develop
      XDEBUG_CONFIG: client_host=host.docker.internal
